# -*- coding: utf-8 -*-
"""Desafio14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPjJe-QU1cw23lDoRaTw71OQHwArS71f
"""

# Instalar o plotnine (se ainda não estiver instalado)
!pip install plotnine
!pip install scikit-misc
# Importar bibliotecas
import pandas as pd
from plotnine import *
from plotnine.data import diamonds


# Visualizar o conjunto de dados
diamonds.head()

# Gráfico de dispersão com suavização (tendência)
(
    ggplot(diamonds, aes(x='carat', y='price')) +
    geom_point(alpha=0.3, color='steelblue') +
    geom_smooth(method='loess', color='red', se=False) +
    labs(
        title='Relação entre Peso (Carat) e Preço (Price) de Diamantes',
        x='Peso (carat)',
        y='Preço (USD)'
    ) +
    theme_minimal()
)

"""Interpretação:

Observa-se uma relação fortemente positiva entre o peso e o preço do diamante. À medida que o peso (carat) aumenta, o preço cresce de forma não linear, sugerindo que diamantes maiores são desproporcionalmente mais caros. Para garantir a qualidade da visualização, utilizei transparência (alpha=0.3) para evitar sobreposição de pontos e adicionei uma curva suavizada (geom_smooth) para evidenciar a tendência.
"""

(
    ggplot(diamonds, aes(x='carat', y='price', color='cut')) +
    geom_point(alpha=0.4) +
    geom_smooth(method='loess', se=False) +
    labs(
        title='Relação entre Peso e Preço por Tipo de Corte',
        x='Peso (carat)',
        y='Preço (USD)',
        color='Corte'
    ) +
    theme_light()
)

"""Conclusão:

A relação entre peso e preço é consistente em todos os cortes, mas há diferenças nos níveis de preço: diamantes com cortes melhores (Ideal, Premium) tendem a apresentar preços mais altos para o mesmo peso. O tipo de corte influencia o valor agregado do diamante, não apenas o tamanho físico.
"""

(
    ggplot(diamonds, aes(x='carat', y='price')) +
    geom_point(alpha=0.3, color='darkblue') +
    geom_smooth(method='loess', se=False, color='red') +
    facet_grid('cut ~ color') +
    labs(
        title='Preço vs Peso por Corte e Cor do Diamante',
        x='Peso (carat)',
        y='Preço (USD)'
    ) +
    theme_bw() +
    theme(
        figure_size=(10, 8),
        subplots_adjust={'wspace': 0.25, 'hspace': 0.35}
    )
)

"""Conclusão:

Ao combinar corte e cor, nota-se que a relação peso-preço se mantém positiva, mas o nível e a inclinação variam entre categorias. Diamantes com corte Ideal e cor D ou E são mais valorizados.
As principais dificuldades envolvem a quantidade de combinações possíveis e o tamanho visual dos gráficos — por isso, foi necessário ajustar o tema e o espaçamento para manter a legibilidade.
"""

(
    ggplot(diamonds, aes(x='carat', y='price', color='clarity')) +
    geom_point(alpha=0.3) +
    geom_smooth(method='loess', se=False) +
    facet_wrap('~cut') +
    labs(
        title='Preço vs Peso por Corte e Clareza',
        x='Peso (carat)',
        y='Preço (USD)',
        color='Clareza'
    ) +
    theme_minimal()
)

"""Análise final:

A combinação de corte, cor e clareza explica boa parte da variação no preço. Diamantes de melhor clareza (IF, VVS1) e melhor corte (Ideal, Premium) tendem a custar mais, mesmo com o mesmo peso. A relação é sempre crescente, mas a taxa de crescimento varia conforme a qualidade geral do diamante.
"""