---
title: "Desafio_05"
author: "Gabriel Belchior"
format: html
editor: visual
---


```{r}
library("RSQLite")
```

```{r}
db = dbConnect(SQLite(),
'disco.db')
db

```

```{r}
dbListTables(db)

```

```{r}
dbListFields(db,
'albums')

```

```{r}
album_db = dbGetQuery(db,
'SELECT * FROM albums')
head(album_db)
```

```{r}
dim(album_db)
```

1:

```{r}
sql = 'SELECT trackid, name, composer, unitprice FROM tracks ORDER BY unitprice'
res = dbGetQuery(db, sql)
head(res)

```

2:

```{r}
sql = 'SELECT city FROM customers ORDER BY city'
ex3a = dbGetQuery(db, sql)
head(ex3a)

```

3:

```{r}
sql = 'SELECT DISTINCT city FROM customers ORDER BY city'
ex3b = dbGetQuery(db, sql)
head(ex3b)

```

4:

```{r}
dbGetQuery(db,
'SELECT name, albumid FROM tracks WHERE albumid=1')
```

5:

```{r}
sql = paste('SELECT name, albumid, mediatypeid FROM tracks'
,
'WHERE mediatypeid IN (1, 2)'
,
'ORDER BY name LIMIT 5')
dbGetQuery(db, sql)
```

6:

```{r}
sql = paste('SELECT trackid, name, albumid FROM tracks'
,
'WHERE albumid IN'
,
'(SELECT albumid FROM albums WHERE artistid==12)'
,
'LIMIT 5')
dbGetQuery(db, sql)
```

7:

```{r}
sql = "SELECT trackid, name FROM tracks WHERE name GLOB '?ere*'"
dbGetQuery(db, sql)
```

8:

```{r}
sql = "SELECT trackid, name FROM tracks WHERE name GLOB '*[0-9]*'"
dbGetQuery(db, sql)

```

9:

```{r}
sql = 'SELECT albumid, COUNT(trackid) FROM tracks GROUP BY albumid'
dbGetQuery(db, sql)

```

10:

```{r}
sql = paste('SELECT albumid, COUNT(trackid)'
,
'FROM tracks GROUP BY albumid'
,
'HAVING albumid=1')
dbGetQuery(db, sql)

```

11:

```{r}
sql = paste('SELECT trackid, name, title FROM tracks'
,
'INNER JOIN albums ON albums.albumid=tracks.albumid')
dbGetQuery(db, sql)


```

